// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNxu_c6Xq4g_87CwvZXMItIKm_vz5Rb4g',
    appId: '1:529403111308:web:1f6eaafe30d6245ae098a9',
    messagingSenderId: '529403111308',
    projectId: 'zainhomeservice',
    authDomain: 'zainhomeservice.firebaseapp.com',
    storageBucket: 'zainhomeservice.appspot.com',
    measurementId: 'G-E233NRPXWM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfEIbsZFcnElaBxdWycfVmZJAojjnTrOk',
    appId: '1:529403111308:android:7582135fe8b5e8c3e098a9',
    messagingSenderId: '529403111308',
    projectId: 'zainhomeservice',
    storageBucket: 'zainhomeservice.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYQXDXANHylsKpYw4rAhCXIq6TdFh6ziI',
    appId: '1:529403111308:ios:d4f4f68b4c319cd0e098a9',
    messagingSenderId: '529403111308',
    projectId: 'zainhomeservice',
    storageBucket: 'zainhomeservice.appspot.com',
    iosBundleId: 'com.example.zainApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYQXDXANHylsKpYw4rAhCXIq6TdFh6ziI',
    appId: '1:529403111308:ios:1314f0f16d5c0c1ae098a9',
    messagingSenderId: '529403111308',
    projectId: 'zainhomeservice',
    storageBucket: 'zainhomeservice.appspot.com',
    iosBundleId: 'com.example.zainApp.RunnerTests',
  );
}
